#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_figs


singularity exec docker://brainlife/mne:1.0.2 python3 main.py

cat << EOF > product.json
{
    "brainlife": [
       {
         "type": "image/png",
	       "name": "overlay plot heartbeats",
         "base64": "$(base64 -w 0 out_figs/plot_overlay_hb.png)"
       },
       {
         "type": "image/png",
	       "name": "overlay plot blinks",
         "base64": "$(base64 -w 0 out_figs/plot_overlay_blinks.png)"
       },
       {
         "type": "image/png",
	       "name": "raw",
         "base64": "$(base64 -w 0 out_figs/s1.png)"
       },
       {
         "type": "image/png",
	       "name": "filtered raw",
         "base64": "$(base64 -w 0 out_figs/s2.png)"
       }
]
}
EOF
