#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=00:30:00
#SBATCH --mem=16G
set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_report


singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py

